import { Product, Order, Delivery, DashboardStats } from './types'

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Premium Headphones',
    sku: 'HP-001',
    price: 199.99,
    quantity: 45,
    category: 'Electronics',
    description: 'High-quality wireless headphones',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'USB-C Cable',
    sku: 'UC-002',
    price: 12.99,
    quantity: 5,
    category: 'Accessories',
    description: 'Durable USB-C charging cable',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Phone Case',
    sku: 'PC-003',
    price: 24.99,
    quantity: 120,
    category: 'Accessories',
    description: 'Protective phone case',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Wireless Charger',
    sku: 'WC-004',
    price: 34.99,
    quantity: 8,
    category: 'Electronics',
    description: 'Fast wireless charging pad',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
]

export const mockOrders: Order[] = [
  {
    id: '1',
    orderNumber: 'ORD-001',
    customerId: 'C1',
    customerName: 'John Doe',
    customerEmail: 'john@example.com',
    customerPhone: '+1234567890',
    items: [
      {
        id: '1',
        productId: '1',
        productName: 'Premium Headphones',
        quantity: 1,
        price: 199.99,
        total: 199.99,
      },
    ],
    subtotal: 199.99,
    tax: 20.00,
    shipping: 10.00,
    total: 229.99,
    status: 'delivered',
    paymentStatus: 'paid',
    shippingAddress: '123 Main St, City, State 12345',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '2',
    orderNumber: 'ORD-002',
    customerId: 'C2',
    customerName: 'Jane Smith',
    customerEmail: 'jane@example.com',
    customerPhone: '+1234567891',
    items: [
      {
        id: '2',
        productId: '3',
        productName: 'Phone Case',
        quantity: 2,
        price: 24.99,
        total: 49.98,
      },
    ],
    subtotal: 49.98,
    tax: 5.00,
    shipping: 5.00,
    total: 59.98,
    status: 'shipped',
    paymentStatus: 'paid',
    shippingAddress: '456 Oak Ave, Town, State 54321',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
]

export const mockDeliveries: Delivery[] = [
  {
    id: '1',
    orderId: '1',
    orderNumber: 'ORD-001',
    status: 'delivered',
    deliveryPersonName: 'Mike Johnson',
    deliveryPersonPhone: '+1234567800',
    location: 'Downtown',
    estimatedDeliveryTime: '2024-08-05 14:00',
    actualDeliveryTime: '2024-08-05 13:45',
    receiptIssued: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
]

export const mockStats: DashboardStats = {
  totalOrders: 12,
  totalRevenue: 3500.50,
  pendingDeliveries: 2,
  completedDeliveries: 10,
  inventoryValue: 15000.00,
  lowStockItems: 2,
}
