import { ArrowUpRight, BatteryCharging, BellRing, Fingerprint, Sparkles } from 'lucide-react'

type BuildStatusProps = { build?: { ready: boolean; label?: string; url?: string } }

export function GlowHero() {
  return (
    <section className="mx-auto grid max-w-6xl items-center gap-12 px-6 pb-20 pt-12 lg:grid-cols-[1fr_0.8fr] lg:px-8 lg:pb-28 lg:pt-24">
      <div>
        <p className="mb-6 font-mono text-xs uppercase tracking-[0.25em] text-primary">A brighter mobile routine</p>
        <h1 className="max-w-xl text-balance text-5xl font-semibold tracking-[-0.06em] text-foreground sm:text-7xl">Make room for your <span className="text-primary">best energy.</span></h1>
        <p className="mt-7 max-w-lg text-pretty text-lg leading-8 text-muted-foreground">Glow turns small daily intentions into a calm, beautifully simple Android experience that keeps you moving forward.</p>
        <div className="mt-9 flex flex-wrap items-center gap-4"><a href="#download" className="rounded-full bg-primary px-6 py-3 font-semibold text-primary-foreground shadow-[0_8px_30px_-12px_var(--primary)] transition-transform hover:scale-105">Download Glow <ArrowUpRight className="ml-1 inline size-4" aria-hidden="true" /></a><a href="#features" className="text-sm font-semibold text-foreground underline decoration-border underline-offset-8 hover:decoration-primary">See what&apos;s inside</a></div>
      </div>
      <div className="relative mx-auto w-full max-w-sm" aria-label="Glow app preview mockup">
        <div className="rounded-[2.5rem] border border-border bg-card p-3 shadow-2xl shadow-primary/10"><div className="overflow-hidden rounded-[2rem] bg-secondary p-5"><div className="flex items-center justify-between text-xs text-muted-foreground"><span>9:41</span><span className="font-mono">GLOW</span></div><div className="mt-16"><Sparkles className="size-8 text-primary" aria-hidden="true" /><p className="mt-5 text-3xl font-semibold tracking-tight text-foreground">Good morning,<br />Alex.</p><p className="mt-3 text-sm leading-6 text-muted-foreground">One clear step is enough to start.</p></div><div className="mt-16 rounded-2xl bg-primary p-4 text-primary-foreground"><p className="text-xs font-medium uppercase tracking-wider opacity-75">Today&apos;s focus</p><p className="mt-2 text-lg font-semibold">Take it outside</p><div className="mt-5 h-1 rounded-full bg-primary-foreground/30"><div className="h-1 w-2/3 rounded-full bg-primary-foreground" /></div></div></div>
        <div className="absolute -right-3 top-16 rounded-xl border border-border bg-card px-3 py-2 text-xs text-foreground shadow-lg"><span className="mr-2 inline-block size-2 rounded-full bg-primary" />Streak: 08 days</div>
      </div>
    </section>
  )
}

const features = [{ icon: Fingerprint, title: 'Feels like you', text: 'A private rhythm that adapts to the way you actually live.' }, { icon: BellRing, title: 'Never noisy', text: 'Gentle nudges arrive when they can help, not when they can interrupt.' }, { icon: BatteryCharging, title: 'Light on battery', text: 'Designed for all-day use, so your habits never cost you your charge.' }]
export function GlowFeatures() { return <section id="features" className="border-y border-border bg-card/50"><div className="mx-auto max-w-6xl px-6 py-20 lg:px-8"><p className="font-mono text-xs uppercase tracking-[0.25em] text-primary">Thoughtfully made</p><h2 className="mt-4 max-w-2xl text-3xl font-semibold tracking-tight text-foreground sm:text-5xl">The quiet tools that make a difference.</h2><div className="mt-12 grid gap-4 md:grid-cols-3">{features.map(({ icon: Icon, title, text }) => <article key={title} className="rounded-2xl border border-border bg-background p-6"><Icon className="size-5 text-primary" aria-hidden="true" /><h3 className="mt-12 text-lg font-semibold text-foreground">{title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{text}</p></article>)}</div></div></section> }

export function BuildStatus({ build = { ready: false, label: 'Build in progress' } }: BuildStatusProps) { const url = build.url ?? process.env.NEXT_PUBLIC_EAS_BUILD_URL ?? '#'; return <section id="build" className="mx-auto max-w-6xl px-6 py-16 lg:px-8"><div className="flex flex-col gap-6 rounded-2xl bg-foreground p-6 text-background sm:flex-row sm:items-center sm:justify-between sm:p-8"><div><p className="font-mono text-xs uppercase tracking-[0.2em] text-primary">EAS build status</p><h2 className="mt-3 text-2xl font-semibold">{build.ready ? 'Your APK is ready.' : build.label ?? 'Build in progress'}</h2><p className="mt-2 text-sm text-background/65">{build.ready ? 'Install the latest Glow build on your Android device.' : 'We&apos;re packaging the latest version for Android.'}</p></div>{build.ready ? <a href="/downloads/glow.apk" className="shrink-0 rounded-full bg-primary px-5 py-3 text-center text-sm font-semibold text-primary-foreground">Download APK</a> : <a href={url} target="_blank" rel="noreferrer" className="shrink-0 rounded-full border border-background/25 px-5 py-3 text-center text-sm font-semibold text-background hover:bg-background/10">Open EAS build <ArrowUpRight className="ml-1 inline size-4" aria-hidden="true" /></a>}</div></section> }

export function DownloadCTA() { return <section id="download" className="mx-auto max-w-6xl px-6 pb-20 lg:px-8"><div className="rounded-3xl border border-primary/30 bg-primary/10 px-6 py-12 text-center sm:px-12"><p className="font-mono text-xs uppercase tracking-[0.25em] text-primary">Ready when you are</p><h2 className="mx-auto mt-4 max-w-xl text-3xl font-semibold tracking-tight text-foreground sm:text-5xl">A little more glow, every day.</h2><a href="/downloads/glow.apk" className="mt-8 inline-block rounded-full bg-primary px-7 py-3 font-semibold text-primary-foreground">Download Glow for Android</a><p className="mt-5 text-xs leading-5 text-muted-foreground">Android only · After downloading, open the APK and allow installs from this source when prompted.</p></div></section> }

export function GlowFooter() { return <footer className="border-t border-border"><div className="mx-auto flex max-w-6xl flex-col gap-3 px-6 py-8 text-xs text-muted-foreground sm:flex-row sm:items-center sm:justify-between lg:px-8"><span className="font-mono font-bold tracking-[0.2em] text-foreground">GLOW<span className="text-primary">.</span></span><span>Built with care for brighter days.</span></div></footer> }
